name: Mirror to Ebrains

on:
  push:
    branches: [ main ]

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: sycnmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "akarmas/sample-ebrains-component"
          source_branch: "maain"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/technical-coordination/members-testing/sample-mirror.git"
          destination_branch: "master"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "akarmas/sample-ebrains-component"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/technical-coordination/members-testing/sample-mirror.git"
          destination_branch: "refs/tags/*"
